name: Code Style Validation

on: pull_request

jobs:
  code_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run detekt
        uses: detekt/detekt-action@v1
        with:
          args: --build-upon-default-config
